### ISSUE TITLE
А как найти chunklist.m3u8

### ISSUE THREAD

**Issue by bobka-dv** [idlesign/webinardump#2]
Здравствуйте 

```
А про использование написано тут: [https://github.com/idlesign/webinardump#использование](https://github.com/idlesign/webinardump#%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)
Что значит «обычный поиск» в данном контексте, увы, непонятно. В инструкции речь шла о необходимости перехода сначала на страницу с конкретным вебинаром.
```

Вот например 
**Отыскать ссылку с record-new/ и запомнить её.**
Захожу  по данной ссылке , нажимаю F12.  ищу поиском "record-new", нахожу сохраняю ссылку 
https://events.webinar.ru/28373707/165353927/record-new/1775044077
**Отыскать ссылку, оканчивающуюся на chunklist.m3u8 и запомнить её.**
Далее пытаюсь найти "chunklist.m3u8" но поиск не дает результатов

**Comment by idlesign** [comment]
Доброго дня.

Тут похоже нужно будет ещё немного руками поработать: по ссылке с record-new, после нажатия на кнопку воспроизведения, продвинуть линейку воспроизведения к моменту начала видео (в вашем случае это примерно после 8 минут). В консоли f12 при этом должны появится запросы к серверу, в том числе и chunklist.

**Comment by bobka-dv** [comment]
Добрый день !
Выдает ошибку. 
Traceback (most recent call last):
  File "/home/dev/webinar/webinarru.py", line 199, in <module>
    run(url_entry=url_entry, url_chunklist=url_chunklist)
  File "/home/dev/webinar/webinarru.py", line 144, in run
    assert 'record-new/' in url_entry, (
AssertionError: Unexpected entry URL format
Given:    https://bm-rx.atatus.com/track/browser/perf/pageload?data=%7B%22nt%22%3A352%2C%22dp%22%3A2923%2C%22pr%22%3A237%2C%22pl%22%3A3512%2C%22timing%22%3A%7B%22ns%22%3A0%2C%22rds%22%3A-1%2C%22rde%22%3A-1%2C%22us%22%3A364%2C%22ue%22%3A378%2C%22fs%22%3A4%2C%22dls%22%3A46%2C%22dle%22%3A46%2C%22cs%22%3A46%2C%22scs%22%3A152%2C%22ce%22%3A252%2C%22hs%22%3A-1%2C%22rqs%22%3A252%2C%22rps%22%3A352%2C%22rpe%22%3A360%2C%22dl%22%3A364%2C%22di%22%3A3188%2C%22dcs%22%3A3226%2C%22dce%22%3A3275%2C%22dc%22%3A3504%2C%22ls%22%3A3504%2C%22le%22%3A3512%7D%2C%22fcp%22%3A3182%2C%22ts%22%3A1689128629255%2C%22apikey%22%3A%22d735e7e3622a423cbbbde0f99ee02b8d%22%2C%22request%22%3A%7B%22url%22%3A%22https%3A%2F%2Fevents.webinar.ru%2Fedubmstu%2F2046495941%2Frecord-new%2F685444666%22%2C%22ua%22%3A%22Mozilla%2F5.0%20(X11%3B%20Linux%20x86_64%3B%20rv%3A109.0)%20Gecko%2F20100101%20Firefox%2F113.0%22%2C%22w%22%3A1600%2C%22h%22%3A797%7D%2C%22connection%22%3Anull%2C%22tags%22%3A%5B%5D%2C%22user%22%3Anull%2C%22aid%22%3A%220c8276a44b084574aed9bfe92c205072%22%2C%22sid%22%3A%2296252a49dd164a72ba0fd5652b09ea06%22%2C%22v%22%3A%22%22%2C%22_v%22%3A%224.4.1-spa%22%7D&amp;callback=atatus._setFeatures&amp;apikey=d735e7e3622a423cbbbde0f99ee02b8d&amp;v=4.4.1-spa.
Expected: https://events.webinar.ru/xxx/yyy/record-new/aaa/bbb

**Comment by idlesign** [comment]
> Выдает ошибку.

Доброго дня.
Ожидаемо, ведь это ссылка не на events.webinar.ru, а на какой-то bm-rx.atatus.com (в браузере у вас шпионов нет случаем?)

**Comment by bobka-dv** [comment]
Сообразил))) не ту ссылку использовал
Еще вопрос.  Перебрал все ссылки для скачки типа chunklist.m3u8
Получилось что по одной качается только видео со звуком докладчика порядка 114 файлов
По другой качается все вместе с презой, трансляции экрана и местами докладчик, порядка 200 файлов, но звука нет(((
По другим ссылкам. либо 0 либо не полные каталоги
Это нормально?
Расширение ts , чем  склеивали?

**Comment by idlesign** [comment]
Со звуком — странное поведение, не встречался.
А ts склеивается сам скрипт при помощи ffmpeg.

**Comment by bobka-dv** [comment]
Спасибо. установил компонент слейка прошла успешно.
Жаль только, что основной файл без звука получился всего на 36 минут , а запись где чисто докладчик 18((( не соеденить (((

**Comment by myaccounthere** [comment]
Добрый день, просьба помочь. 
не могу найти ссылку, содержащую chunklist.m3u8 или chunklist или m3u8, даже прокрутив видео до середины или до конца. 

ссылка  https://events.webinar.ru/...

**Comment by idlesign** [comment]
> не могу найти ссылку, содержащую chunklist.m3u8 или chunklist или m3u8, даже прокрутив видео до середины или до конца.

Странно. Возможно что-то упускаете из виду. Обычно после 10-15 минут ссылки уже обнаруживаются.

**Comment by myaccounthere** [comment]
Не сочтите за труд, можете открыть мою ссылку и проверить?

**Comment by idlesign** [comment]
> Не сочтите за труд, можете открыть мою ссылку и проверить?

chunklist есть. Проверьте не фильтруются ли в отладочной панели браузера запросы разных типов.

**Comment by nonameformr** [comment]
Такая же проблема, не находит chunklist
https://events.webinar.ru/27034215/131317973/record-new/682412387
Можете помочь?

**Comment by StarikovSN** [comment]
Нашел "chunklist" на вкладке "Network"
![image](https://github.com/idlesign/webinardump/assets/115574933/1812c129-3a8e-4563-b525-d7a8dda350c6)

...но потом словил ошибку:
Traceback (most recent call last):
  File "C:\Users\Семья\PycharmProjects\pythonProject\webinar\main.py", line 199, in <module>
    run(url_entry=url_entry, url_chunklist=url_chunklist)
  File "C:\Users\Семья\PycharmProjects\pythonProject\webinar\main.py", line 168, in run
    dump_dir.mkdir(exist_ok=True)
  File "C:\Users\Семья\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\Семья\\PycharmProjects\\pythonProject\\webinar\\Продвижение через рекламу у блогеров 2023-08-02 15:08:03'

Process finished with exit code 1

**Comment by idlesign** [comment]
> ...но потом словил ошибку:

В целом ожидаемо, если учесть, что в описании (https://github.com/idlesign/webinardump#зависимости) сказано про Unix, но не про Windows. 

Если вдруг есть желание адаптировать код, чтобы он запускался на разных платформах, то можно прислать запрос на слияние (pull request) с подправленным кодом — рассмотрим, вольём, будет работать %)

**Comment by StarikovSN** [comment]
> > ...но потом словил ошибку:
> 
> В целом ожидаемо, если учесть, что в описании ([https://github.com/idlesign/webinardump#зависимости](https://github.com/idlesign/webinardump#%D0%B7%D0%B0%D0%B2%D0%B8%D1%81%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D0%B8)) сказано про Unix, но не про Windows.
> 
> Если вдруг есть желание адаптировать код, чтобы он запускался на разных платформах, то можно прислать запрос на слияние (pull request) с подправленным кодом — рассмотрим, вольём, будет работать %)

Спасибо за ответ. Сорян я тут редкий гость и даже без базовых знаний, но "открытый код" даже таким юзерам как я иногда помогает решать задачи, которые перед нами возникают, не прибегая к помощи программистов;) спасибо! Если допилите, чтобы можно было использовать под винду я думаю мейби и пригодится кому либо, кроме меня. А там вам решать;)

**Comment by nonameformr** [comment]
> Такая же проблема, не находит chunklist https://events.webinar.ru/27034215/131317973/record-new/682412387 Можете помочь?

я нашел, даже несколько)
скачал, но у меня почему то не показывается презентация, только камера выступающего
